include:
  - board: mriya_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT=y -DZMK_EXTRA_MODULES=${ZMK_CONFIG}/..
  - board: mriya_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DZMK_EXTRA_MODULES=${ZMK_CONFIG}/..
  - board: nice_nano_v2
    shield: mriya_dongle dongle_display
    cmake-args: -DZMK_EXTRA_MODULES=${ZMK_CONFIG}/..
  - board: nice_nano_v2
    shield: settings_reset
    cmake-args: -DZMK_EXTRA_MODULES=${ZMK_CONFIG}/..
