# Увеличиваем максимальную длину имени слоя
CONFIG_ZMK_KEYMAP_LAYER_NAME_MAX_LEN=30

# Настройки блокировки
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=y
CONFIG_ZMK_STUDIO_LOCK_IDLE_TIMEOUT_SEC=600
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=y

# Настройки производительности
CONFIG_ZMK_STUDIO_TRANSPORT_BLE_PREF_LATENCY=10
CONFIG_ZMK_STUDIO_RPC_THREAD_STACK_SIZE=2048
CONFIG_ZMK_STUDIO_RPC_RX_BUF_SIZE=64
CONFIG_ZMK_STUDIO_RPC_TX_BUF_SIZE=128

# Дополнительные настройки ZMK Studio
CONFIG_ZMK_STUDIO_PHYSICAL_LAYOUT=y
CONFIG_ZMK_STUDIO_PHYSICAL_LAYOUT_FILE="boards/arm/mriya/mriya.json" 