# Донгл является центральным узлом split-клавиатуры.
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# USB + BLE на донгле.
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# Поддержка настройки через ZMK Studio.
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_TRANSPORT_BLE_PREF_LATENCY=10
CONFIG_ZMK_STUDIO_RPC_THREAD_STACK_SIZE=2048
CONFIG_ZMK_STUDIO_RPC_RX_BUF_SIZE=64
CONFIG_ZMK_STUDIO_RPC_TX_BUF_SIZE=128
